# Define the following environment variables in the Travis config
#   - IBM_CLOUD_APIKEY
#   - IBM_CLOUD_ORG

sudo: required
language: python
python: 
  - "3.8"
dist: bionic

branches:
  only:
    - master


env:
  - IBM_CLOUD_REGION="us-south" 
  - IBM_CLOUD_FRONTEND_SPACE="xaip"


install:
  - sudo apt update
  - sudo apt install nodejs
  - sudo apt upgrade nodejs
  - node -v
  - curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
  - ibmcloud --version
  - ibmcloud cf install
  - ibmcloud login --apikey ${IBM_CLOUD_APIKEY} -r ${IBM_CLOUD_REGION}
  - export NODE_OPTIONS=--max_old_space_size=8192


script:
  - ibmcloud target -s ${IBM_CLOUD_FRONTEND_SPACE} -o ${IBM_CLOUD_ORG}
  - cd ${TRAVIS_BUILD_DIR}/website
  - yarn install --ignore-engines
  - yarn build
  - ibmcloud cf push
  